
on:
 push:
   branches:
     - master







jobs:
   build:
     runs-on: ubuntu-latest



     steps:
       - name: 'after folder contents'
         run: ls
         
       - uses: actions/checkout@v3  


       - name: 'after folder contents'
         run: ls
