
on:
 push:
   branches:
     - master







jobs:
   build:
     runs-on: ubuntu-latest



     steps:
       
       - name: 'printing folder contents'
         run: ls
       -uses: action/checkout@v3  

       
       - name: 'after folder contents'
         run: ls
